-- MySQL Script generated by MySQL Workbench
-- 12/01/16 14:16:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Conselho_classe
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Conselho_classe
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `conselho_classe` DEFAULT CHARACTER SET utf8 ;
USE `conselho_classe` ;

-- -----------------------------------------------------
-- Table `Conselho_classe`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Conselho_classe`.`Professor` (
  `idProfessor` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  `Materia_leciona` VARCHAR(45) NULL,
  `Matricula` VARCHAR(45) NULL,
  PRIMARY KEY (`idProfessor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Conselho_classe`.`Questionário`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Conselho_classe`.`Questionário` (
  `idQuestionário` INT NOT NULL AUTO_INCREMENT,
  `Data` DATE NULL,
  PRIMARY KEY (`idQuestionário`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Conselho_classe`.`Turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Conselho_classe`.`Turma` (
  `idTurma` INT NOT NULL AUTO_INCREMENT,
  `Sigla` VARCHAR(45) NULL,
  `Questionário_idQuestionário` INT NOT NULL,
  `Turno` VARCHAR(45) NULL,
  PRIMARY KEY (`idTurma`, `Questionário_idQuestionário`),
  INDEX `fk_Turma_Questionário1_idx` (`Questionário_idQuestionário` ASC),
  CONSTRAINT `fk_Turma_Questionário1`
    FOREIGN KEY (`Questionário_idQuestionário`)
    REFERENCES `Conselho_classe`.`Questionário` (`idQuestionário`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Conselho_classe`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Conselho_classe`.`Aluno` (
  `idAluno` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  `Matricula` VARCHAR(45) NULL,
  `Turma_idTurma` INT NOT NULL,
  PRIMARY KEY (`idAluno`, `Turma_idTurma`),
  INDEX `fk_Aluno_Turma_idx` (`Turma_idTurma` ASC),
  CONSTRAINT `fk_Aluno_Turma`
    FOREIGN KEY (`Turma_idTurma`)
    REFERENCES `Conselho_classe`.`Turma` (`idTurma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Conselho_classe`.`Conselho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Conselho_classe`.`Conselho` (
  `idConselho` INT NOT NULL AUTO_INCREMENT,
  `Data` DATE NULL,
  `Questionário_idQuestionário` INT NOT NULL,
  PRIMARY KEY (`idConselho`, `Questionário_idQuestionário`),
  INDEX `fk_Conselho_Questionário1_idx` (`Questionário_idQuestionário` ASC),
  CONSTRAINT `fk_Conselho_Questionário1`
    FOREIGN KEY (`Questionário_idQuestionário`)
    REFERENCES `Conselho_classe`.`Questionário` (`idQuestionário`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Conselho_classe`.`Professor_has_Conselho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Conselho_classe`.`Professor_has_Conselho` (
  `Professor_idProfessor` INT NOT NULL,
  `Conselho_idConselho` INT NOT NULL,
  PRIMARY KEY (`Professor_idProfessor`, `Conselho_idConselho`),
  INDEX `fk_Professor_has_Conselho_Conselho1_idx` (`Conselho_idConselho` ASC),
  INDEX `fk_Professor_has_Conselho_Professor1_idx` (`Professor_idProfessor` ASC),
  CONSTRAINT `fk_Professor_has_Conselho_Professor1`
    FOREIGN KEY (`Professor_idProfessor`)
    REFERENCES `Conselho_classe`.`Professor` (`idProfessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professor_has_Conselho_Conselho1`
    FOREIGN KEY (`Conselho_idConselho`)
    REFERENCES `Conselho_classe`.`Conselho` (`idConselho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Conselho_classe`.`Observação`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Conselho_classe`.`Observação` (
  `idObservação` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NULL,
  `Professor_idProfessor` INT NOT NULL,
  `Aluno_idAluno` INT NOT NULL,
  `Aluno_Turma_idTurma` INT NOT NULL,
  `Texto` VARCHAR(200) NULL,
  PRIMARY KEY (`idObservação`, `Professor_idProfessor`, `Aluno_idAluno`, `Aluno_Turma_idTurma`),
  INDEX `fk_observação_Professor1_idx` (`Professor_idProfessor` ASC),
  INDEX `fk_observação_Aluno1_idx` (`Aluno_idAluno` ASC, `Aluno_Turma_idTurma` ASC),
  CONSTRAINT `fk_observação_Professor1`
    FOREIGN KEY (`Professor_idProfessor`)
    REFERENCES `Conselho_classe`.`Professor` (`idProfessor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_observação_Aluno1`
    FOREIGN KEY (`Aluno_idAluno` , `Aluno_Turma_idTurma`)
    REFERENCES `Conselho_classe`.`Aluno` (`idAluno` , `Turma_idTurma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Conselho_classe`.`Resposta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Conselho_classe`.`Resposta` (
  `idResposta` INT NOT NULL AUTO_INCREMENT,
  `Data` DATE NULL,
  PRIMARY KEY (`idResposta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Conselho_classe`.`Questões`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Conselho_classe`.`Questões` (
  `idQuestões` INT NOT NULL AUTO_INCREMENT,
  `Data` DATE NULL,
  `Questionário_idQuestionário` INT NOT NULL,
  `Resposta_idResposta` INT NOT NULL,
  PRIMARY KEY (`idQuestões`, `Questionário_idQuestionário`, `Resposta_idResposta`),
  INDEX `fk_Questões_Questionário1_idx` (`Questionário_idQuestionário` ASC),
  INDEX `fk_Questões_Resposta1_idx` (`Resposta_idResposta` ASC),
  CONSTRAINT `fk_Questões_Questionário1`
    FOREIGN KEY (`Questionário_idQuestionário`)
    REFERENCES `Conselho_classe`.`Questionário` (`idQuestionário`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Questões_Resposta1`
    FOREIGN KEY (`Resposta_idResposta`)
    REFERENCES `Conselho_classe`.`Resposta` (`idResposta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
